### PR TITLE
After saveReady module

### PR DESCRIPTION
**Pull request by LostKobrakai**
Sorry for all those commits, used github to preview it :smile:

### CODE REVIEW

**Comment by owzim** [comment]
Hey, thanks for the contribution! :+1: 

Couple of things I'd like to mention:
* We use plural lingo on tags when applicable, so it would be `modules` instead of `module`
* I am unsure about the title, can we make it shorter? also: "do things", hmmm ... :)
* We use 4 space indenting for all the other recipes, it'd be cool if you could change that.
* Perhaps also backtick the path in the text?

Looking forward to the revision.

**Comment by owzim** [comment]
@LostKobrakai If you're on Mac you can preview the MarkDown with [Mou.app](http://25.io/mou/) unfortunately it does not support language ids for code blocks, still. 

Not sure about Windows, a quick Google resulted in [MarkdownPad](http://markdownpad.com/) being pretty popular.

**Comment by LostKobrakai** [comment]
I've Marked 2 installed, just was lazy.

**Comment by marcus-herrmann** [comment]
And if you don't want to install a particular app for this, and you're using Sublime Text or PHPStorm (or any other JetBrains IDE), there are plugins available, for example:

* https://github.com/revolunet/sublimetext-markdown-preview
* https://plugins.jetbrains.com/plugin/?idea&id=5970

**Comment by owzim** [comment]
The Sublime Text plugin works very spotty (no refresh an such), and the output has always been weird for me, and totally different from GitHub.

**Comment by owzim** [comment]
Can we somehow merge it without all the sub commits?

**Comment by LostKobrakai** [comment]
I don't think. At least not without me deleting my fork and adding the file newly as a whole thing.

**Pull request closed without merging**
